export const COSTO_HABITUAL_TRANSACCION = 1000;
export const COSTO_DIA_NO_HABIL_TRANSACCION = COSTO_HABITUAL_TRANSACCION + (COSTO_HABITUAL_TRANSACCION * 0.20); // 20% more
export const TRANSACCION_ORIGEN = 'cuenta origen';
export const TRANSACCION_DESTINO = 'cuenta destino';